name: Build and Publish

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ dev ]
    paths:
      - 'releases/**'
      - 'snapshots/**'
      - 'plugins/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Generate Repository Index
        run: |
          git pull
          node generate-repo-data.js

      - name: Commit and Push Index Changes
        run: |
          git config --global user.name 'GitHub Actions'
          if ! git diff --quiet --cached; then
            git push
          else
            echo "No changes to commit"
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
